service: techical-challenge
frameworkVersion: '3'
planetsTableName: Planets

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
          Resource:
            - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:planetsTableName}"
  environment:
    SWAPI_BASE_URL: https://swapi.py4e.com/api/
    PLANET_TABLE_NAME: ${self:planetsTableName}

functions:
  getAllPlanets:
    handler: src/handler.getAllPlanets
    events:
      - httpApi:
          path: /planets
          method: get
  getPlanet:
    handler: src/handler.getPlanet
    events:
      - httpApi:
          path: /planets/{id}
          method: get
  createPlanet:
    handler: src/handler.createPlanet
    events:
      - httpApi:
          path: /planets
          method: post
resources:
  Resources:
    DynamoDBTableAssets:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:planetsTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH